# Todays Topic: Dual Quaternions and Screw Theory
---
<br>

### Content:

- Rotation Matrices Introduction
- Transformation Matrices Introduction
- from Complex Numbers to Dual Quaternions
    - Complex Numbers
    - Quaternions
    - Dual Quaternions

- Screw Theory
    - Basics
    - Dual Quaternion Transformation
    - Application To Kinematics

- Comparison Dual Quaternions vs Transformation Matrices

<br><br><br><br>

## Rotation Matrices: Representation of Rotations in 3D
---
<br>

A **rotation matrix** is a special orthogonal matrix used to rotate vectors in a Euclidean space. In 3D, a rotation matrix $R \in \mathbb{R}^{3 \times 3}$ represents rotations around an axis or between coordinate frames.


#### Properties:
- A **3D rotation matrix** $ R $ is a square $ 3 \times 3 $ matrix that satisfies:
   $$
   R^T R = I \quad \text{and} \quad \det(R) = 1
   $$
- **Orthogonality**: Columns (and rows) of $ R $ are orthonormal, meaning:
  - Each column has a unit length: $ \|R_i\| = 1 $,
  - Columns are mutually perpendicular, and represent the frame axis $\vec{x}$, $\vec{y}$, $\vec{z}$
- **Rotation Composition**: The product of two rotation matrices $ R_1 $ and $ R_2 $ is also a rotation matrix:
  $$
  R = R_1 \cdot R_2
  $$

#### Basic Rotation Matrices:
In 3D, rotations can be decomposed around each principal axis:
1. **Rotation around the $ x $-axis** by angle $ \theta $:
   $$
   R_x(\theta) = \begin{bmatrix} 
   1 & 0 & 0 \\ 
   0 & \cos(\theta) & -\sin(\theta) \\ 
   0 & \sin(\theta) & \cos(\theta) 
   \end{bmatrix}
   $$

In [1]:
from helper import *


def Rx(theta):
    Rx = np.array([ [1, 0,                         0],
                    [0, np.cos(theta), -np.sin(theta)],
                    [0, np.sin(theta), np.cos(theta)]])
    return Rx

print(Rx(1))

[[   1.000    0.000    0.000]
 [   0.000    0.540   -0.841]
 [   0.000    0.841    0.540]]


2. **Rotation around the $ y $-axis** by angle $ \theta $:
   $$
   R_y(\theta) = \begin{bmatrix} 
   \cos(\theta) & 0 & \sin(\theta) \\ 
   0 & 1 & 0 \\ 
   -\sin(\theta) & 0 & \cos(\theta) 
   \end{bmatrix}
   $$

In [2]:
def Ry(theta):
    Ry = np.array([ [np.cos(theta),  0, np.sin(theta)],
                    [0,              1,             0],
                    [-np.sin(theta), 0, np.cos(theta)]])
    return Ry

print(Ry(1))

[[   0.540    0.000    0.841]
 [   0.000    1.000    0.000]
 [  -0.841    0.000    0.540]]


3. **Rotation around the $ z $-axis** by angle $ \theta $:
   $$
   R_z(\theta) = \begin{bmatrix} 
   \cos(\theta) & -\sin(\theta) & 0 \\ 
   \sin(\theta) & \cos(\theta) & 0 \\ 
   0 & 0 & 1 
   \end{bmatrix}

In [3]:
def Rz(theta):
    Rz = np.array([ [np.cos(theta), -np.sin(theta), 0],
                    [np.sin(theta),  np.cos(theta), 0],
                    [0,              0,             1]])
    return Rz

print(Rz(1))

[[   0.540   -0.841    0.000]
 [   0.841    0.540    0.000]
 [   0.000    0.000    1.000]]


In [4]:
from helper import *

def interactive_plot(angle1, angle2, angle3):

    fig, ax = create_3d_plot()

    # compose rotation matrix
    rotation_matrix = Rx(angle1)@Ry(angle2)@Rz(angle3)
    
    # Update plot
    draw_frame(ax, [0, 0, 0], rotation_matrix)
    plt.show()

slider_R1 = create_angle_slider("Rx")
slider_R2 = create_angle_slider("Ry")
slider_R3 = create_angle_slider("Rz")

ui = widgets.VBox([slider_R1, slider_R2, slider_R3])
out = widgets.interactive_output(interactive_plot, {"angle1": slider_R1, "angle2": slider_R2, "angle3": slider_R3})

# Display the UI
display(out, ui)


Output()

## Transformation Matrices: Combining Rotation and Translation in 3D
---
<br>

A **transformation matrix** in 3D is a $4 \times 4$ matrix that combines rotation and translation, allowing for the movement and orientation of objects in a 3D space.

#### Properties:
- A **3D transformation matrix** $ T \in \mathbb{R}^{4 \times 4} $ has the form:
  $$
  T = \begin{bmatrix} 
  R & \vec{p} \\ 
  0 & 1 
  \end{bmatrix}
  $$
  where:
  - $ R \in \mathbb{R}^{3 \times 3} $ is a rotation matrix,
  - $ \vec{p} = \begin{bmatrix} p_x \\ p_y \\ p_z \end{bmatrix} $ is a translation vector,
  
- **Rotation and Translation**: Transformation matrices combine rotation (through $R$) and translation (through $\vec{p}$), enabling both orientation and displacement.
- **Matrix Multiplication**: Applying multiple transformations $ T_1 $, $ T_2 $, etc., is achieved by matrix multiplication:
  $$
  T_{\text{combined}} = T_1 \cdot T_2
  $$


In [5]:
import numpy as np

def Transformation(R, p):
    T = np.eye(4,4)
    T[:3, :3] = R
    T[:3, 3] = p

    return T

R = Ry(1)
p = np.array([1, 2, 3])

print(Transformation(R, p))

[[   0.540    0.000    0.841    1.000]
 [   0.000    1.000    0.000    2.000]
 [  -0.841    0.000    0.540    3.000]
 [   0.000    0.000    0.000    1.000]]


In [6]:
from helper import *

def interactive_plot(angle1, angle2, angle3, x, y, z):

    fig, ax = create_3d_plot()

    # compose rotation matrix
    rotation_matrix = Rx(angle1)@Ry(angle2)@Rz(angle3)
    position = np.array([x, y, z])

    T = Transformation(rotation_matrix, position)

    # Update plot
    draw_frame(ax, [x, y, z], rotation_matrix)
    plt.show()

slider_R1 = create_angle_slider("Rx")
slider_R2 = create_angle_slider("Ry")
slider_R3 = create_angle_slider("Rz")
x_slider, y_slider, z_slider = create_position_sliders()

ui = widgets.VBox([slider_R1, slider_R2, slider_R3,x_slider, y_slider, z_slider])
out = widgets.interactive_output(interactive_plot, {"angle1": slider_R1, "angle2": slider_R2, "angle3": slider_R3, "x": x_slider, "y": y_slider, "z": z_slider})

# Display the UI
display(out, ui)

Output()

## Complex Numbers
---

<br>

Complex Numbers extend the Real Numbers by another component. They are 2 Dimensional and can be expressed in the so-called *Complex Plane*

Recall Eulers Formula : 
$$ z = re^{i\theta} = r(\cos(\theta) + i \sin(\theta)) = a + ib $$

<br>

Note:
- $i$ is called the complex unit and $i^2 = -1$
- $Re(z) = a$ is called the *real part* 
- $Im(z) = b$ is called the *complex part*
- $\|z\| = r = \sqrt{a^2 + b^2}$
- all complex numbers $z$ with $\|z\|=1$ are part of the subspace $S^1$
- $S^1$ is the unit-circle in the Complex Plane


In [7]:
from helper import *


def interactive_plot(angle, norm):

    fig, ax = create_complex_plane()

    # compute the complex number
    complex_number = norm*np.exp(1j * angle)

    # Compute complex components
    real_part = complex_number.real
    imag_part = complex_number.imag
    complex_text = f"$ {norm:.2f} \\cdot e^{{i{angle:.2f}}} = {real_part:.2f} + {imag_part:.2f}i$"
    
    # Plot the cross at the origin
    ax.plot(real_part, imag_part, marker='x', color='red', markersize=10)
    ax.plot([0, real_part], [0, imag_part], color='blue')
    ax.plot([real_part,real_part], [0, imag_part], color='orange')
    ax.plot([0, real_part], [0, 0], color='orange')
    
    ax.text(-1.2, 2.2, f"Complex Number: {complex_text}", fontsize=12, va='top', ha='left')
    plt.show()

# Define sliders for angle and norm
slider_width = '70%'
angle_slider = widgets.FloatSlider(value=0.0, min=-6.28, max=6.28, step=0.01, description="Angle", layout={'width': slider_width})
norm_slider = widgets.FloatSlider(value=1, min=0.1, max=1.9, step=0.01, description="Norm", layout={'width': slider_width})

# Link the sliders to the plot function using interactive_output
ui = widgets.VBox([angle_slider, norm_slider])
out = widgets.interactive_output(interactive_plot, {"angle": angle_slider, "norm": norm_slider})

# Display the UI
display(out, ui)


Output()

## Complex Numbers: Rotation Composition in 2D
---
<br>

Recall the multiplication rule of exponentials:

$$ a^b \cdot a^c = a^{b+c} $$

<br><br>


From this, the composition of 2D rotations via Complex Numbers can be derived as follows:

$$
\begin{align*}
z_3 &= z_1 \cdot z_2 \\
&= e^{i \theta_1} \cdot e^{i \theta_2}  \\
&= e^{i (\theta_1 + \theta_2)} \\
\end{align*}
$$

<br>


## Complex Numbers: Vector Rotation in 2D
---
<br>

A complex number $u \in S^1$ can be used to rotate any 2D vector $\vec{x} \in \mathbb{R}^2$.

For this, $\vec{x} = (x_1, x_2)^T$ has to be written as a complex number $x_c$:

$$ x_c = x_1 + i x_2 $$


Rotation by angle $\theta$ can be achieved by premultiplying $u(\theta)$:

$$
\begin{align*}
x_{c, \; \text{rotated}} &= u(\theta) \cdot x_c \\
&= e^{i \theta} \cdot (x_1 + i x_2) \\
&= (\cos(\theta) + i\sin(\theta)) \cdot (x_1 + i x_2) \\
&= \cos(\theta)x_1 + i \cos(\theta)x_2 + i \sin(\theta)x_1 + i^2 \sin(\theta)x_2 \\
&= \cos(\theta)x_1 - \sin(\theta)x_2 + i (\cos(\theta)x_2 + \sin(\theta)x_1)
\end{align*}
$$

Thus, the rotated vector in its $\mathbb{R}^2$ form is:

$$\vec{x}_{\text{rotated}} = ((\cos(\theta)x_1 - \sin(\theta)x_2),  (\cos(\theta)x_2 + \sin(\theta)x_1))^T$$


<br>

In [8]:
from helper import *

# Define the interactive plot function
def interactive_plot(x1, x2, angle, norm):
    
    fig, ax = create_complex_plane()
    
    # Original vector as complex number
    x_c = complex(x1, x2)

    u = norm*np.exp(1j * angle)
    rotated_vector = u * x_c
    real_rotated = rotated_vector.real
    imag_rotated = rotated_vector.imag

    # Compute complex components
    real_part = u.real
    imag_part = u.imag
    complex_text = f"$ {norm:.2f} \\cdot e^{{i{angle:.2f}}}$"
    
    # plot the rotated vecotr
    ax.plot([0, real_rotated], [0, imag_rotated], color="red", linestyle="--", label="Rotated Vector")
    ax.plot(real_rotated, imag_rotated, marker='x', color='red', markersize=10)

    # Plot the cross at the origin
    ax.plot(real_part, imag_part, marker='x', color='red', markersize=10, label="Origin")
    # Plot the vector
    ax.plot([0, real_part], [0, imag_part],color='blue')
    
    # Display the complex number in LaTeX
    ax.text(-0.8, 2.3, f"Complex Number: {complex_text}", fontsize=12, va='top', ha='left')
    plt.show()

slider_width = '70%'

x1_input = widgets.FloatText(value=-0.8, description="x1", layout={'width': slider_width})
x2_input = widgets.FloatText(value=1.2, description="x2", layout={'width': slider_width})

angle_slider = widgets.FloatSlider(value=0, min=-6.28, max=6.28, step=0.01, description="Angle", layout={'width': slider_width})
norm_slider = widgets.FloatSlider(value=1, min=0.1, max=1.9, step=0.01, description="Norm", layout={'width': slider_width})

# Link the sliders to the plot function using interactive_output
ui = widgets.VBox([x1_input, x2_input, angle_slider, norm_slider])
out = widgets.interactive_output(interactive_plot, {"x1": x1_input, "x2": x2_input, "angle": angle_slider, "norm": norm_slider})

# Display the UI
display(out, ui)


Output()

### Complex Numbers: Exponential and Logarithmic Map

--- 
<br><br>

<div style="display: flex; justify-content: space-between;">

<!-- Left column for text -->
<div style="width: 68%;">

Starting from the complex number $z$ given in *Polar Coordinates*:


$$ z = re^{i \theta} $$

The Logarithmic of a complex number is given as:

$$ log(z) = log(r) + i \theta $$
    
<br><br>

Under the assumption that $z \in S^1$ ($r=1$) we can define the Exponential and Logarithmic map of a complex Number:

Exponential map:

$$ i\mathbb{R} \to S^1 $$
$$ i\theta \to e^{i\theta} $$


Logarithmic map:
 
 $$ S^1  \to i\mathbb{R} $$
 $$ e^{i \theta} \to i\theta $$
</div>

<!-- Right column for image -->
<div style="width: 28%;">
    <img src="./data/exp_log_s1.png" alt="calibration scheme" style="max-width: 600px; width: 100%; display: block; margin-left: auto; margin-right: auto;margin-top: 100px;">
    <p style="text-align: center; font-style: italic; margin-top: 10px;">Exp and Log map on the complex unit circle.</p>
</div>

</div>

<br><br><br>

## Quaternions
---
<br>

Quaternions extend the Complex Numbers to 3D. A Quaternion is given as:


 $$ q = w + xi + yj + zk $$

Note:
- $w$: *real part*
- $x$, $y$, $z$: *imaginary parts*
- $i$, $j$, $k$: *imaginary units*, satisfying
    - $i^2 = j^2 = k^2 = ijk = -1$
    - $ij = k$, $jk = i$, $ki = j$ (and cyclic permutations)
- $\|q\| = \sqrt{w^2 + x^2 + y^2 + z^2}$
- if $\|q\| = 1$, then $q \in S^3$ which is the subspace of *unit quaternions*
- $S^3$ is the unit sphere in 4D space (hypersphere)


Notations:

- Standard Form: $q = w + xi + yj + zk$
- Vector Notation: $q = (w, x, y, z)$
- Real & Complex Part: $q = (w, \vec{v})$, where $\vec{v} = [x, y, z]$ is called the *complex vector* of $q$

In [9]:
from neura_dual_quaternions import Quaternion

#Example: identity quaternion
quat = Quaternion(0,1,0,0)

print(quat)
print(quat.asRotationMatrix())

Quaternion(0.000, 1.000, 0.000, 0.000)
[[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]


## Quaternions: Axis Angle Representation
---

<br>

Given an unit-length rotation axis $\hat{r} = [r_x, r_y, r_z]$ and an angle $\theta$, the corresponding unit quaternion $q =(w, \vec{v})$ is given by:

$$
\begin{align*}
q &= (\cos\left(\frac{\theta}{2}\right), \sin\left(\frac{\theta}{2}\right)\hat{r})\\
&= \cos\left(\frac{\theta}{2}\right) +  \sin\left(\frac{\theta}{2}\right) \left(r_xi + r_yj + r_zk\right) \\
\end{align*}
$$

Note: 
- Similarity to Complex Numbers $z = \cos(\theta) + \sin(\theta)i$.
- To avoid rotational singularities in 3D, a unit quaternion is set up with the half angle $\frac{\theta}{2}$.

In [10]:
from neura_dual_quaternions import Quaternion

# rotation axis
r = np.array([0,1,0])

theta = 1 # unit: rad

q = Quaternion.fromAxisAngle(theta, r)

print(q)

print("Quaternion Rotation:")
print(q.asRotationMatrix())

Quaternion(0.878, 0.000, 0.479, 0.000)
Quaternion Rotation:
[[   0.540    0.000    0.841]
 [   0.000    1.000    0.000]
 [  -0.841    0.000    0.540]]


In [11]:
from helper import *

def interactive_plot(angle, azimuth, elevation):

    fig, ax = create_3d_plot()

    direction = spherical_coordinates(azimuth, elevation)

    # Construct unit quaternion from axis-angle representation
    quaternion = Quaternion.fromAxisAngle(angle, direction)
    
    #  Update plot elements with new quaternion rotation
    create_quiver(ax, [0, 0, 0], direction, 1, 'grey')
    draw_frame(ax, [0, 0, 0], quaternion.asRotationMatrix())
    plt.show()

angle_slider, azimuth_slider, elevation_slider = create_quaternion_sliders()

ui = widgets.VBox([angle_slider, azimuth_slider, elevation_slider])
out = widgets.interactive_output(interactive_plot, {"angle": angle_slider, "azimuth": azimuth_slider, "elevation": elevation_slider})

# Display the UI
display(out, ui)


Output()

### Quaternions: Rotations Composition in 3D
---
<br>

Similarly to rotation matrices, unit quaternions $q \in S^3$ can be used to describe successive rotations.

$$ q_4 = q_1 \otimes q_2 \otimes q_3 $$

where $q_4$ combines the rotations of $q_1$, $q_2$, $q_3$ in given order.
<br>

**Note**:
- quaternion multiplication is not commutative, order matters!
- analogy Rotationmatrices: $R_4 = R_1 \cdot R_2 \cdot R_3$

<br>

In [12]:
from helper import *

def interactive_plot(angle_x, angle_y, angle_z):

    fig, ax = create_3d_plot()

    # Construct unit quaternion from axis-angle representation
    quaternion_x = Quaternion.fromAxisAngle(angle_x, np.array([1,0,0]))
    quaternion_y = Quaternion.fromAxisAngle(angle_y, np.array([0,1,0]))
    quaternion_z = Quaternion.fromAxisAngle(angle_z, np.array([0,0,1]))

    quaternion = quaternion_x*quaternion_y*quaternion_z

    #  Update plot elements with new quaternion rotation
    draw_frame(ax, [0, 0, 0], quaternion.asRotationMatrix())
    plt.show()

slider_width = '70%'
angle_x_slider = widgets.FloatSlider(value=0, min=-6.28, max=6.28, step=0.01, description="Rx", layout={'width': slider_width})
angle_y_slider = widgets.FloatSlider(value=0, min=-6.28, max=6.28, step=0.01, description="Ry", layout={'width': slider_width})
angle_z_slider = widgets.FloatSlider(value=0, min=-6.28, max=6.28, step=0.01, description="Rz", layout={'width': slider_width})

ui = widgets.VBox([angle_x_slider, angle_y_slider, angle_z_slider])
out = widgets.interactive_output(interactive_plot, {"angle_x": angle_x_slider, "angle_y": angle_y_slider, "angle_z": angle_z_slider})

# Display the UI
display(out, ui)

Output()

### Quaternions: Vector Rotation in 3D
---
<br>

Similarly to complex numbers, a unit quaternion $q \in S^3$ can be used to rotate any 3D vector $\vec{x} \in \mathbb{R}^3$.

For this, $\vec{x} = (x_1, x_2, x_3)^T$ has to be written as a *pure quaternion* $\bar{q}_x$:

$$ \bar{q}_x = (0, \vec{x} ) = (0 + x_1i + x_2j + x_3k)$$

<br>

because of the half angle $\frac{\theta}{2}$, the rotation quaternion has to be applied twice to achieve full rotation.

$$ \bar{q}_{x, \text{rotated}} = q_r \otimes \bar{q}_x \otimes q_r^* $$

<br>

**Note**:
- a *pure quaternion* is any quaternion with real part $w=0$.
- $\otimes$ denotes the quaternion multiplication.
- $q^*$ denotes the quaternion conjugate. $q^* = (w, -\vec{v})$.
- for unit quaternions: $q^* = q^{-1}$.
- analogy rotation matrices: $\vec{x}_r = R\vec{x}$.

<br>


### Quaternions: Double Cover Property
---
<br>

<div style="display: flex; justify-content: space-between;">

<!-- Left column for text -->
<div style="width: 58%;">

One of the unique and beneficial properties of Quaternions is the *Double Cover Property*.

This property states that any unit quaternion $q$ and its negation $-q$ represent the **same orientation** in 3D space. Although they map to the same final orientation, $q$ and $-q$ define **different paths of rotation**. This can be thought of as two ways to reach the same orientation: a **long path** or a **short path**, depending on the choice of $q$ or $-q$.

#### Why is this Useful?
- *Avoidance of Ambiguities*: Quaternions prevent **gimbal lock** and allow smooth transitions between orientations.
- *Interpolation Control*: The Double Cover Property allows quaternions to perform efficient **spherical linear interpolation (SLERP)**, with control over short and long rotation paths.

</div>

<!-- Right column for image -->
<div style="width: 38%;">
    <img src="./data/quaternion_sphere.png" alt="calibration scheme" style="max-width: 600px; width: 100%; display: block; margin-left: auto; margin-right: auto;margin-top: 100px;">
    <p style="text-align: center; font-style: italic; margin-top: 10px;">Long and Short Path Interpolation on the Quaternion Hypersphere.</p>
</div>

</div>


In [13]:
from helper import *

#Example: Constructor and Antipodal Property
q1 = Quaternion(1,0,0,0)
q2 = Quaternion(.900, 0.000, 0.000, 0.434)*(1)

def interactive_plot(s):

    fig, ax = create_3d_plot(q2)

    qm = Quaternion.slerp(q1, q2, s)    
    
    draw_frame(ax, [0,0,0], qm.asRotationMatrix())
    
    plt.show()

s_slider = create_slider("s", 0, 0, 1)


ui = widgets.VBox([s_slider])
out = widgets.interactive_output(interactive_plot, {"s": s_slider})

# Display the UI
display(out, ui)

Output()

### Quaternions: Exponential and Logarithmic Map
---
<br>

<div style="display: flex; justify-content: space-between;">

<div style="width: 68%;">


Given the product of **angle** and **rotation axis** $\vec{v} = \frac{\theta}{2}\hat{r}$, the exponential map of a unit quaternion is defined similarly to the exponential of a complex number:

#### Exponential map of a unit quaternion
   $$ e^{\vec{v}} = e^{\frac{\theta}{2}\hat{r}} = \cos(\|\vec{v}\|) + \frac{\vec{v}}{\|\vec{v}\|} \sin(\|\vec{v}\|)$$

Note:
- map: $\mathbb{R}^3 \to S^3$
- $\|\vec{v}\| = \frac{\theta}{2}$
- zero-angle singularity $\|\vec{v}\| = 0$ (can be approximated with tailor series expansion)
- similarity to axis angle contructor
- similarity to complex numbers


#### Logarithmic map of a unit quaternion

The logarithm of $q = (w, \vec{v})$ is defined as:


$$ \log(q) =  \arccos\left(w\right)\frac{\vec{v}}{\|\vec{v}\|} = \frac{\theta}{2}\hat{r} $$

Note:
- map: $S^3 \to \mathbb{R}^3$
- zero-angle singularity $ \|\vec{v}\| = 0$ (can be approximated with tailor series expansion)

<br>
<br><br>
</div>

<!-- Right column for image -->
<div style="width: 28%;">
    <img src="./data/quaternion_exp_log.png" alt="calibration scheme" style="max-width: 600px; width: 100%; display: block; margin-left: auto; margin-right: auto;margin-top: 100px;">
    <p style="text-align: center; font-style: italic; margin-top: 10px;">Exp and Log map on the Quaternion Hypersphere.</p>
</div>



### Dual Quaternions
---

Dual Quaternions are a system for representing transformations in three dimensions, composed of two Quaternions $q_r$ and $q_d$.


Dual-Quaternion: $$ \underline{\xi} = q_r + \epsilon q_d $$

Features:
- Quaternion $q_r$: **real part**
- Quaternion $q_d$: **dual part**
- dual unit $\epsilon$: $\epsilon^2 = 0$ and $\epsilon \neq 0$
- the Subspace of dual quaternions that can describe Homogeneous Transformations is called $\mathbb{H}$
- if $\underline{\xi} \in \mathbb{H}$ then $\xi$ is called a unit dual quaternion
- similarity $\epsilon$ vs. $i$
    
<br>

Notation:
- Standard: $\underline{\xi} = q_r + \epsilon q_d$
- Real & Complex Part: $\underline{\xi} = (w_r, \vec{v}_r) + \epsilon (w_d, \vec{v}_d)$
- Sub-Vectorized: $\underline{\xi} = (w_r, x_r, y_r, z_r) + \epsilon (w_d, x_d, y_d, z_d)$
- Vectorized: $[\underline{\xi}]_{vec} = (w_r, x_r, y_r, z_r, w_d, x_d, y_d, z_d)^T$


In [14]:
from neura_dual_quaternions import Quaternion, DualQuaternion

q_r = Quaternion(0,1,0,0)

q_d = Quaternion (0, 2, 1, 2)  

dq = DualQuaternion(q_r, q_d)

print(dq)
print("")
print(dq.asVector())
print("")
print(dq.asTransformation())

DualQuaternion(Real: Quaternion(0.000, 1.000, 0.000, 0.000), Dual: Quaternion(0.000, 2.000, 1.000, 2.000))

[[0]
 [1]
 [0]
 [0]
 [0]
 [2]
 [1]
 [2]]

[[   1.000    0.000    0.000    0.000]
 [   0.000   -1.000    0.000   -4.000]
 [   0.000    0.000   -1.000    2.000]
 [   0.000    0.000    0.000    1.000]]


### Dual Quaternions: Basic Transformation
---
<br>

Given the unit quaternion $ q_r$ and the pure quaternion $\bar{t}$ the dual quaternion transformation can be defined:

<br>

First Translation, then Rotation:
$$ 
\underline{\xi} = q_r + \epsilon \frac{1}{2} \bar{t} \otimes q_r 
$$
    

<br>

Note:
- $q_r = (w, \vec{v})$: defines rotation/orientation of frame
- $\bar{t} = (0,x,y,z)$: defines position of frame

<br>

Example:

In [15]:
# Update function for the sliders
def interactive_plot(angle, azimuth, elevation, x, y, z):

    fig, ax = create_3d_plot()
    
    direction = spherical_coordinates(azimuth_slider.value, elevation_slider.value)
    
    # construct unit quaternion from axis angle
    q_r = Quaternion.fromAxisAngle(angle_slider.value, direction)
    
    # set position vector
    pos = [x_slider.value, y_slider.value, z_slider.value]
    
    dq = DualQuaternion.fromQuatPos(q_r, pos)
    
    # update plot
    create_quiver(ax, dq.getPosition().flatten(), direction,1, 'grey')
    draw_frame(ax, dq.getPosition().flatten(), q_r.asRotationMatrix())
    plt.show()

    
angle_slider, azimuth_slider, elevation_slider = create_quaternion_sliders()
x_slider, y_slider, z_slider = create_position_sliders()

ui = widgets.VBox([angle_slider, azimuth_slider, elevation_slider, x_slider, y_slider, z_slider])
out = widgets.interactive_output(interactive_plot, {"angle": angle_slider, "azimuth": azimuth_slider, "elevation": elevation_slider,
                                                        "x": x_slider, "y": y_slider, "z": z_slider})

# Display the UI
display(out, ui)


Output()

### Dual Quaternions: Multiplication $\otimes$
---
<br>

    
Dual Quaternion Multiplication is similar to the multiplication of Transformation matrices 

$$
\underline{\xi}_2^0= \underline{\xi}_1^0 \otimes \underline{\xi}_2^1 
$$

corresponds to: 

$$
T_2^0= T_1^0 \cdot T_2^1 
$$

<br>

#### Dual Quaternion Multiplication $\otimes$

The multiplication of two dual quaternions $ \underline{\xi}_1$ and $\underline{\xi}_2$ can be done as follows:

$$
\underline{\xi}_1 \otimes \underline{\xi}_2 = (q_r^{(1)} + \epsilon q_d^{(1)}) \otimes (q_r^{(2)} + \epsilon q_d^{(2)})
$$

$$
\underline{\xi}_1 \otimes \underline{\xi}_2 = (q_r^{(1)} \otimes q_r^{(2)}) + \epsilon(q_r^{(1)} \otimes q_d^{(2)} + q_d^{(1)} \otimes q_r^{(2)}) + \epsilon^2(q_d^{(1)} \otimes q_d^{(2)})
$$

with $\epsilon^2 = 0$ the new dual quaternion is written like 

$$
\underline{\xi}_3= (q_r^{(1)} \otimes q_r^{(2)}) + \epsilon(q_r^{(1)} \otimes q_d^{(2)} + q_d^{(1)} \otimes q_r^{(2)})
$$

<br><br><br>

### Dual Quaternions: Exponential and Logarithmic Map
---
<br>

Given the product of **dual angle** $\underline{\theta} = \theta + \epsilon d$ and **screw axis** $\bar{\underline{s}}$, the exponential map of a dual quaternion is defined similarly to the exponential of a Quaternion: 

The exponential map is defined as:
<br>

$$
\underline{\xi} = e^{\frac{\underline{\theta}}{2}\bar{\underline{s}}} = \cos(\frac{\underline{\theta}}{2}) +  \sin(\frac{\underline{\theta}}{2})\bar{\underline{s}}
$$


Note:
- map: $\mathbb{R}^6 \to \mathbb{H}$
- $\bar{\underline{s}} = (0 + s_1i + s_2j + s_3k) + \epsilon(0 + s_4i + s_5j + s_6k)$ is a pure dual quaternion
- $\bar{\underline{s}} \in \mathbb{R}^6$
- zero-angle singularity $\|\frac{\underline{\theta}}{2}\bar{\underline{s}}\| = 0$ (can be approximated with tailor series expansion)
- similarity to unit quaternions (+ dual maths)

<br>

The logarithmic map of $\underline{\xi} = q_r + \epsilon q_d$ is defined as:


$$ \log(\underline{\xi}) = \frac{\underline{\theta}}{2}\bar{\underline{s}} $$

Note:
- map: $\mathbb{H} \to \mathbb{R}^6$
- zero-angle singularity $ \|\frac{\underline{\theta}}{2}\bar{\underline{s}}\| = 0$ (can be approximated with tailor series expansion)

<br><br><br>

## Screw Theory
---
<br>
<div style="display: flex; justify-content: space-between;">
<div style="width: 48%;">

Screw Theory is a more advanced alternative to the Denavit-Hartenberg Convention.

Key Concepts:
- *screw axis* $\vec{s}$
- *screw motion* around the screw axis $\vec{s}$
- Tranformations from exponential map
- Can handle revolute and prismatic joints without distinction
    
</div>

<!-- Right column for image -->
<div style="width: 48%;">
    <img src="./data/screw.png" alt="calibration scheme" style="max-width: 700px; width: 100%; display: block; margin-left: auto; margin-right: auto;margin-top: 100px;">
    <p style="text-align: center; font-style: italic; margin-top: 10px;">Screw Axis example.</p>
</div>

</div>

<br><br>

### Screw Theory: The Screw Axis
--- 

<br>

The screw axis $\vec{s} \in \mathbb{R}^6$ is defined from a rotation axis $\hat{r}$ and a position $\vec{p}$



$$ \vec{s} = (\hat{r}, \; \vec{p} \times \hat{r}) = (\hat{r}, \; \vec{m})$$

Here, $\vec{m} = \vec{p} \times \hat{r}$ is called the *moment of the line*.


Followingly, the screw axis is represented as **pure dual quaternion** $\bar{\underline{s}} = (0, \hat{r}) + \epsilon(0, \vec{m}) = \hat{r} + \epsilon \vec{m}$





In [16]:
#Example
r = np.array([0,1,0])
pos = np.array([0,0,2])


s = DualQuaternion.screwAxis(*r, *pos)
print("screw axis: ", s)

screw axis:  DualQuaternion(Real: Quaternion(0.000, 0.000, 1.000, 0.000), Dual: Quaternion(0.000, -2.000, 0.000, 0.000))


in combination with the dual angle $\underline{\theta} = \theta + \epsilon d$, the Screw Transformation can be computed:

$$ \underline{\xi} = e^{\frac{\underline{\theta}}{2}\bar{\underline{s}}} $$

The exponent can be computed via the application of dual maths:
$$
\begin{align*}
\frac{\underline{\theta}}{2}  \cdot \bar{\underline{s}} &= 0.5 \cdot (\theta + \epsilon d) \cdot (\hat{r} + \epsilon\vec{m})\\
&= 0.5 \cdot (\theta \cdot \hat{r}) + \epsilon (\theta \cdot \vec{m} + d \cdot \hat{r}) + \epsilon^2(d \cdot \vec{m}) \\
&= 0.5 \cdot (\theta \cdot \hat{r}) + \epsilon (\theta \cdot \vec{m} + d \cdot \hat{r})  \\
\end{align*}
$$

Notes:
- $\theta$: rotation around screw axis
- $d$: translation along screw axis

In [17]:
from helper import *

frame = DualQuaternion.fromQuatPos(Quaternion(1,0,0,0), [0.3,.5,.5])

def interactive_plot(angle, azimuth, elevation, x, y, z):

    fig, ax = create_3d_plot()
    
    rotation_axis = spherical_coordinates(azimuth, elevation)
    
    # set position vector
    pos = [x, y, z]
    
    screw_axis = DualQuaternion.screwAxis(*rotation_axis, *pos)
    
    theta = 0 
    d = 0.1*angle
   
    exponent = DualQuaternion(screw_axis.real*theta, screw_axis.dual*theta + screw_axis.real*d)
    screw_transformation = DualQuaternion.exp(0.5*exponent)
    
    frame_transformed = screw_transformation*frame
    
    create_quiver(ax, pos, rotation_axis, 1, 'grey') 
    ax.plot([pos[0]-rotation_axis[0]*2, pos[0]+rotation_axis[0]*2], [pos[1]-rotation_axis[1]*2, pos[1]+rotation_axis[1]*2], [pos[2]-rotation_axis[2]*2, pos[2]+rotation_axis[2]*2], "--", linewidth = 1, c = "black")
    ax.plot([0, pos[0]], [0, pos[1]], [0, pos[2]], "--", linewidth = 1, c = "k")
    draw_frame(ax, frame.getPosition().flatten(), frame.real.asRotationMatrix())
    draw_frame(ax, frame_transformed.getPosition().flatten(), frame_transformed.real.asRotationMatrix())

    plt.show()


angle_slider, azimuth_slider, elevation_slider = create_quaternion_sliders()
x_slider, y_slider, z_slider = create_position_sliders()

ui = widgets.VBox([angle_slider, azimuth_slider, elevation_slider, x_slider, y_slider, z_slider])
out = widgets.interactive_output(interactive_plot, {"angle": angle_slider, "azimuth": azimuth_slider, "elevation": elevation_slider,
                                                        "x": x_slider, "y": y_slider, "z": z_slider})

# Display the UI
display(out, ui)


Output()

## Screw Theory: Application To Kinematics
--- 
<div style="font-family: 'Helvetica Neue', Arial, sans-serif; display: flex; justify-content: space-between;">

<!-- Left column for text -->
<div style="width: 58%;">

<br>

1. Get the geometric information of the robot we want to model:

    <br>
    
    | Link | Rotation Axis  | Position        |
    |------|----------------|-----------------|
    | 1    | $(0,0,1)$     | $(0,0,0)$       |
    | 2    | $(0,1,0)$     | $(0,0,0.438)$   |
    | 3    | $(0,0,1)$     | $(0,0,0.438)$   |
    | 4    | $(0,1,0)$     | $(0,0,1.138)$   |
    | 5    | $(0,0,1)$     | $(0,0,1.138)$   |
    | 6    | $(0,1,0)$     | $(0,0,1.838)$   |
    | 7    | $(0,0,1)$     | $(0,0,1.838)$   |

    <br>
    
    The Endeffector Frame $M$ is defined as a Dual Quaternion transformation with orientation of $q_r = (1,0,0,0)$ and position of $\bar{t} = (0,0,0,1.953)$.

<br><br>

2. Set up screw axis from the geometric information

3. Compute exponential map to get screw transformations

4. Compose the tTransformations to get Forward Kinematics 

</div>

<!-- Right column for image -->
<div style="width: 38%;">
    <img src="./data/maira_screw_axis.png" alt="calibration scheme" style="max-width: 500px; width: 100%; display: block; margin-left: auto; margin-right: auto;margin-top: 10px;">
</div>

</div>

In [18]:
from neura_dual_quaternions import Quaternion, DualQuaternion

s1 = DualQuaternion.screwAxis(*[0, 0, 1], *[0, 0, 0])
s2 = DualQuaternion.screwAxis(*[0, 1, 0], *[0, 0, 0.438])
s3 = DualQuaternion.screwAxis(*[0, 0, 1], *[0, 0, 0.438])
s4 = DualQuaternion.screwAxis(*[0, 1, 0], *[0, 0, 1.138])
s5 = DualQuaternion.screwAxis(*[0, 0, 1], *[0, 0, 1.138])
s6 = DualQuaternion.screwAxis(*[0, 1, 0], *[0, 0, 1.838])
s7 = DualQuaternion.screwAxis(*[0, 0, 1], *[0, 0, 1.838])

M = DualQuaternion.fromQuatPos(Quaternion(1,0,0,0), [0, 0, 1.953])

print(s1)

DualQuaternion(Real: Quaternion(0.000, 0.000, 0.000, 1.000), Dual: Quaternion(0.000, 0.000, 0.000, 0.000))




with the screws $\bar{\underline{s}}_i$ and the angle $\theta_i$ we can now define the dual quaternion transformations $\underline{\xi}_i$ which correspond to motion around each robotic joint

$$
\underline{\xi}_i = e^{\frac{\underline{\theta}_i}{2}\bar{\underline{s}}_i} 
$$

with these transformations we can then define the transformation between the baseframe and the TCP $ \underline{\xi}_{TCP}^0 $

$$ 
\underline{\xi}_{TCP}^0 = (\Pi_{i = 0}^{n = 7} \underline{\xi}_i) \otimes M
$$


In [19]:
from helper import *

def forward_kinematics(theta):
    x1 = DualQuaternion.exp(0.5*theta[0]*s1)
    x2 = DualQuaternion.exp(0.5*theta[1]*s2)
    x3 = DualQuaternion.exp(0.5*theta[2]*s3)
    x4 = DualQuaternion.exp(0.5*theta[3]*s4)
    x5 = DualQuaternion.exp(0.5*theta[4]*s5)
    x6 = DualQuaternion.exp(0.5*theta[5]*s6)
    x7 = DualQuaternion.exp(0.5*theta[6]*s7)
    
    return x1*x2*x3*x4*x5*x6*x7*M

theta = np.array([1,1,1,1,1,1,1])
print(forward_kinematics(theta))
print(forward_kinematics(theta).asTransformation())

DualQuaternion(Real: Quaternion(-0.701, -0.000, 0.658, 0.275), Dual: Quaternion(-0.506, -0.106, -0.435, -0.249))
[[  -0.017    0.386   -0.922    0.060]
 [  -0.386    0.849    0.362    1.218]
 [   0.922    0.362    0.134    0.768]
 [   0.000    0.000    0.000    1.000]]


In [20]:
from helper import *

# add function to update the model and the 'real' robot
def update_robot(q1, q2, q3, q4, q5, q6, q7):
    
    joint_angles = np.array([q1, q2, q3, q4, q5, q6, q7])
    
    maira.q = joint_angles
    
    T_ee.T = forward_kinematics(joint_angles).asTransformation()
    
    env.step()

# Make and instance of the Swift simulator and open it
env = Swift()
env.launch(realtime=False, browser = "notebook")

# Create a MAiRA model 
maira = rtb.models.URDF.Maira7M()

# show the TCP position computed from the FK as well
T_ee = sg.Axes(0.15, pose = forward_kinematics(maira.q).asTransformation())

# Add model Robot to the environment
env.add(maira)
env.add(T_ee)


# display sliders to make the robot move
show_sliders(update_robot)

interactive(children=(FloatSlider(value=0.0, description='joint angle 1', layout=Layout(width='80%'), max=3.14…

##  Comparison: Dual Quaternions vs Transformation Matrices
---



Why should I start using Quaternions and Dual Quaternions?

1. #### Efficiency: 

    Dual Quaternions are generally 20-30% more efficient than DH Transformation Matrices.
    This can be explained by the following table:
    
    <br>

    Computation | Storage | Multiplication | Addition | Sin/Cos
    ------------|---------|----------------|----------|--------
    DH Tf.      | 16      |  6             |    0     |   4
    DQ Tf.      |   8     |  15            |    3     |   2
    Tf. Mat Mult.|  -     |   64           |    48    |   0
    DQ Mult     |   -     |    48          |    40    |   0

<br>

2. #### Double Cover Property:
    
    Dual Quaternions inherit the **Double Cover Property** from the Quaternions, allowing for singularity free handling and more control during Interpolation.
    This is especially helpful in the inverse Kinematics and Motion planning of  Cobots.

<br>

3. #### Ease of Use:

    While the implementation of Transformation matrices is more straight-forward, the application of Dual Quaternions (in combination with Screw Theory) allows for more flexible and intuitve usage, i.e. during set up of the *Forward Kinematics*.

    <br>

<div style="font-family: 'Helvetica Neue', Arial, sans-serif; padding: 120px; text-align: center; margin-left: 0px;">

<!-- Introduction -->
<div style="max-width: 1100px;font-family: 'Helvetica Neue', Arial, sans-serif; margin-left: -50px;">
    <!-- Making the headline a link to the Neura Robotics website -->
<h1 style="font-size: 5.5em; margin-bottom: 15px;">Thank you for your Attention!</h1>

</div>
</div>


<div style="font-family: 'Helvetica Neue', Arial, sans-serif;">
<h2 style="border-bottom: 2px solid #ddd; padding-bottom: 10px;">Contact Information</h2>

<!-- Lecturer: Jens Temminghoff -->
<h4>Lecturer: Jens Temminghoff</h4>
<p>jens.temminghoff@neura-robotics.com</p>

<!-- Human Resources Department -->
<h4>Human Resources: Florian Fackelmeyer</h4>
<p>florian.fackelmeyer@neura-robotics.com</p>

<!-- Company: Neura Robotics -->
<h4>Neura Robotics</h4>
<p>For more information, visit our <a href="https://www.neura-robotics.com">official website</a> or contact our team directly. We're always eager to collaborate and bring new ideas to life!</p>
</div>
<br><br><br><br>